Repository FTL13/New-FTL13, pull requests merged in 2018-09, with the labels that each got.

#1 first
  _FTL/README.md
  _FTL/icons/obj/96x96.dmi
  ftl13.dme
Labels: Good first PR

#50 Makes ftl13.dme load tgstation.dme
  ftl13.dme
Labels: DME Edit

#88 [MIRROR] 40441: Allows E-Katana to be stored in the back slot
  code/modules/ninja/energy_katana.dm
Labels: Upstream PR Merged

#89 [MIRROR] 40499: Fixes economy runtime with ID cards not on mobs
  code/modules/economy/account.dm
Labels: Upstream PR Merged

#90 [MIRROR] 40372: Adds RPGs to Nuke Ops
  code/game/mecha/equipment/weapons/weapons.dm
  code/modules/projectiles/ammunition/caseless/rocket.dm
  code/modules/projectiles/boxes_magazines/internal/grenade.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/launchers.dm
  code/modules/projectiles/projectile/special/rocket.dm
  code/modules/research/designs/mecha_designs.dm
  code/modules/spells/spell_types/rightandwrong.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/ammo.dmi
  icons/obj/projectiles.dmi
Labels: Upstream PR Merged

#91 [MIRROR] 40454: [s] Fixes ore redemption exploit
  code/modules/mining/machine_redemption.dm
Labels: Upstream PR Merged
